name: 'pull-request'
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  pr_build_with_tests:
    name: PR build with tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm dependencies 
        run: npm install
      - name: Jest coverage report
        run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

